# Generated by Django 4.0.1 on 2022-01-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLRecord',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('short_url', models.TextField()),
                ('long_url', models.TextField()),
            ],
        ),
    ]
